'use client';

import { FormEvent, useState } from 'react';
import { motion, useReducedMotion } from 'framer-motion';
import { ArrowDown, ArrowRight, ArrowUpRight, Bot, Braces, BriefcaseBusiness, Check, ChevronRight, Command, Cpu, Github, Layers3, Linkedin, Mail, Menu, MessageSquare, MousePointer2, Radio, Sparkles, TerminalSquare, Workflow, X } from 'lucide-react';
import { CAPABILITIES, PROFILE, SERVICES, STACK, SOCIALS } from '../content';
import { PROJECTS, REPOSITORIES } from '../data/projects';

const ease = [0.22, 1, 0.36, 1] as const;
function Reveal({ children, delay = 0, className = '' }: { children: React.ReactNode; delay?: number; className?: string }) {
  const reduce = useReducedMotion();
  return <motion.div className={className} initial={reduce ? false : { opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.15 }} transition={{ duration: 0.65, delay, ease }}>{children}</motion.div>;
}

function Nav() {
  const [open, setOpen] = useState(false);
  const links = [['About', '#about'], ['Projects', '#projects'], ['GitHub', '#github'], ['Services', '#services'], ['Contact', '#contact']];
  return <header className="nav-wrap"><nav className="nav container" aria-label="Main navigation"><a href="#home" className="brand"><span className="brand-mark">K<span>.</span></span><span>KAPILASH</span></a><div className={`nav-links ${open ? 'nav-open' : ''}`}>{links.map(([label, href]) => <a key={label} onClick={() => setOpen(false)} href={href}>{label}</a>)}</div><div className="nav-actions"><a className="icon-link social-desktop" href={SOCIALS.github} target="_blank" rel="noreferrer" aria-label="GitHub"><Github size={17}/></a>{SOCIALS.linkedin && <a className="icon-link social-desktop" href={SOCIALS.linkedin} target="_blank" rel="noreferrer" aria-label="LinkedIn"><Linkedin size={17}/></a>}<a href="#contact" className="button button-small">Let’s talk <ArrowUpRight size={14}/></a><button className="menu-toggle" aria-label={open ? 'Close navigation' : 'Open navigation'} aria-expanded={open} onClick={() => setOpen(!open)}>{open ? <X/> : <Menu/>}</button></div></nav></header>;
}

function MissionPreview() {
  const [tab, setTab] = useState('Mission');
  const side = [{ icon: Layers3, name: 'Overview' }, { icon: Radio, name: 'Mission' }, { icon: MessageSquare, name: 'Evidence' }, { icon: Workflow, name: 'Simulator' }, { icon: TerminalSquare, name: 'Event log' }, { icon: Braces, name: 'Settings' }];
  return <motion.div className="preview-shell" initial={{ opacity: 0, scale: .97, y: 16 }} animate={{ opacity: 1, scale: 1, y: 0 }} transition={{ duration: .85, delay: .2, ease }}>
    <div className="preview-glow"/><div className="app-window"><div className="app-top"><div className="window-controls"><i/><i/><i/></div><div className="window-title"><span className="mini-brand"><Command size={13}/></span> Mars Research AI OS <span className="top-muted">— mission workspace</span></div><span className="version">MVP</span></div>
      <div className="app-body"><aside className="app-sidebar"><div className="app-logo"><span className="mini-brand"><Command size={14}/></span><span>Mars Research</span></div><div className="workspace-label">MISSION WORKSPACE <ChevronRight size={12}/></div>{side.map(({ icon: Icon, name }) => <button key={name} className={`side-item ${tab === name ? 'side-active' : ''}`} onClick={() => setTab(name)}><Icon size={14}/>{name}{name === 'Mission' && <span className="side-dot"/>}</button>)}<div className="sidebar-bottom"><span className="avatar-small">M</span><span><b>Research session</b><small>Source trails on</small></span><span className="online-dot"/></div></aside>
        <div className="app-main"><div className="app-main-head"><div><div className="eyebrow">MISSION CONTROL <span className="task-id">· PREVIEW</span></div><h3>Rover route review</h3></div><span className="running-pill"><i/> Read-only</span></div><div className="agent-message"><div className="agent-icon"><Sparkles size={15}/></div><div><span className="agent-label">MISSION BRIEF <span>·</span> SIMULATION</span><p>Compare route candidates to the selected science targets. Mission decisions remain advisory.</p></div></div><div className="tool-card"><div className="tool-head"><span><Radio size={13}/> Mission simulator</span><span className="tool-success"><Check size={11}/> replayable</span></div><div className="tool-command"><span className="prompt-char">›</span> science targets <span className="separator">→</span> route candidates</div><div className="tool-output"><span>Rover telemetry</span><span className="output-dim">Safety controls active</span></div></div><div className="app-composer"><span>Explore mission evidence…</span><div><span>LOCAL</span><button aria-label="Explore evidence"><ArrowUpRight size={14}/></button></div></div><div className="app-foot"><span><span className="online-dot"/> Mission preview</span><span><Cpu size={11}/> Evidence-linked <span className="separator">·</span> local</span></div></div></div></div>
    <div className="float-chip chip-workspace"><span className="chip-icon"><Braces size={14}/></span><span><b>Research sources</b><small>Evidence trail available</small></span><span className="online-dot"/></div><div className="float-chip chip-tasks"><span className="task-check"><Check size={12}/></span><span><b>Event timeline</b><small>Replayable simulation</small></span></div>
  </motion.div>;
}

function ProjectArtwork({ visual, highlights, featured = false }: { visual: string; highlights: string[]; featured?: boolean }) {
  const iconMap: Record<string, typeof Radio> = { mission: Radio, workflow: Workflow, risk: Cpu, map: MousePointer2, school: Layers3, leads: Bot, sports: Check, finance: Braces };
  const Icon = iconMap[visual] ?? Layers3;
  return <div className={`project-art project-art-${visual} ${featured ? 'project-art-featured' : ''}`} aria-hidden="true">
    <div className="project-art-grid"/>
    <div className="project-art-top"><span className="project-count">REPOSITORY / {visual.toUpperCase()}</span><span className="project-art-icon"><Icon size={20}/></span></div>
    <div className="project-schematic"><span className="schematic-line"/><span className="schematic-node"><Icon size={21}/></span><span className="schematic-node schematic-node-small"><Command size={15}/></span><span className="schematic-node schematic-node-end"><Check size={15}/></span><div className="schematic-tags">{highlights.slice(0,3).map((highlight) => <span key={highlight}>{highlight}</span>)}</div></div>
  </div>;
}

function ProjectCard({ project, index, compact = false }: { project: (typeof PROJECTS)[number]; index: number; compact?: boolean }) {
  const featured = Boolean(project.featured);
  return <article className={`project-card project-${project.visual} ${featured && !compact ? 'project-card-featured' : ''} ${compact ? 'project-card-compact' : ''}`}>
    {!compact && <ProjectArtwork visual={project.visual} highlights={project.highlights ?? []} featured={featured}/>}
    <div className="project-content">
      <div className="project-meta"><span>{project.category}</span>{project.status && <span className="project-status">{project.status}</span>}</div>
      <div className="project-title-row"><div><h3>{project.name}</h3><span className="ownership-label">{project.ownershipLabel}</span></div><a href={project.githubUrl} target="_blank" rel="noreferrer" className="project-link" aria-label={`Open ${project.name} on GitHub`}><ArrowUpRight size={17}/></a></div>
      <p>{project.description}</p>
      {featured && !compact && project.highlights && <ul className="project-highlights">{project.highlights.map((highlight) => <li key={highlight}><Check size={13}/>{highlight}</li>)}</ul>}
      <div className="tech-chips">{project.technologies.map((tech) => <span key={tech}>{tech}</span>)}</div>
      <div className="project-links"><a href={project.githubUrl} target="_blank" rel="noreferrer"><Github size={13}/> View on GitHub <ArrowUpRight size={12}/></a>{project.liveUrl && <a href={project.liveUrl} target="_blank" rel="noreferrer">Live demo <ArrowUpRight size={12}/></a>}</div>
    </div>
    {compact && <ProjectArtwork visual={project.visual} highlights={project.highlights ?? []}/>}
    <span className="project-order">{String(index + 1).padStart(2,'0')}</span>
  </article>;
}

export default function Home() {
  const handleForm = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const subject = encodeURIComponent(`Project inquiry from ${form.get('name') || 'website'}`); const body = encodeURIComponent(`Name: ${form.get('name')}\nEmail: ${form.get('email')}\nCompany: ${form.get('company') || 'Not provided'}\n\nProject:\n${form.get('project')}`); window.location.href = `mailto:${PROFILE.email}?subject=${subject}&body=${body}`; };
  return <main id="home"><Nav/>
    <section className="hero section-pad"><div className="hero-grid-bg"/><div className="container hero-layout"><div className="hero-copy"><Reveal><div className="availability"><span className="online-dot"/> OPEN TO SELECT PROJECTS <span className="avail-divider"/> REMOTE · WORLDWIDE</div><div className="hero-kicker"><span className="kicker-line"/>AI SOFTWARE ENGINEER</div><h1>Building useful<br/><span className="headline-accent">software systems</span><br/>for real problems<span className="period">.</span></h1><p className="hero-lede">I’m Kapilash, an AI/software developer from Sri Lanka. I build and experiment with intelligent software, research systems, automation tools, developer infrastructure, and full-stack products.</p><p className="hero-sub">I learn by building real projects — and share that work openly on GitHub.</p><div className="hero-actions"><a className="button" href="#contact">Start a conversation <ArrowUpRight size={16}/></a><a className="button button-quiet" href="#projects">Explore my work <ArrowDown size={15}/></a></div><div className="hero-social"><span>FIND ME ON</span><a href={SOCIALS.github} target="_blank" rel="noreferrer"><Github size={15}/> GitHub <ArrowUpRight size={12}/></a>{SOCIALS.linkedin && <a href={SOCIALS.linkedin} target="_blank" rel="noreferrer"><Linkedin size={15}/> LinkedIn <ArrowUpRight size={12}/></a>}</div></Reveal></div><div className="hero-visual"><MissionPreview/></div></div><div className="container hero-bottom"><span><span className="scroll-mark"/> SCROLL TO EXPLORE</span><span>INDEPENDENT DEVELOPER <span className="sep">/</span> SRI LANKA</span></div></section>

    <section className="signal-strip"><div className="container signal-inner"><span className="signal-label">FOCUSED ON</span>{['RESEARCH SYSTEMS','DEVELOPER TOOLS','FULL-STACK APPS','OPEN SOURCE'].map((x,i)=><span className="signal-item" key={x}><span className="signal-dot">0{i+1}</span>{x}</span>)}</div></section>

    <section id="projects" className="section-pad section-projects"><div className="container"><Reveal><div className="section-heading"><div><div className="section-overline"><span>01</span> PROJECTS BUILT</div><h2>Real work.<br/><span>Open source.</span></h2></div><p>Selected systems from my public work. Every project links to its repository; live demos appear only where a deployment is listed and responding.</p></div></Reveal><div className="project-grid">{PROJECTS.map((project, i) => <Reveal key={project.slug} delay={i * .06} className={project.featured ? 'project-featured' : ''}><ProjectCard project={project} index={i}/></Reveal>)}</div></div></section>
    <section id="github" className="section-pad section-github"><div className="container"><Reveal><div className="github-heading"><div><div className="section-overline"><span>02</span> MY GITHUB</div><h2>Open source &amp;<br/><span>experiments.</span></h2><p>Explore the software, AI experiments, developer tools, automation systems, and research projects I’ve built and published on GitHub.</p></div><a className="button" href={PROFILE.githubUrl} target="_blank" rel="noreferrer"><Github size={15}/> View GitHub profile <ArrowUpRight size={14}/></a></div></Reveal><div className="repo-grid">{[...PROJECTS, ...REPOSITORIES].map((project, i) => <Reveal key={`repo-${project.slug}`} delay={(i % 4) * .035}><ProjectCard project={project} index={i} compact/></Reveal>)}</div></div></section>

    <section id="services" className="section-pad section-services"><div className="container"><Reveal><div className="section-heading"><div><div className="section-overline"><span>03</span> WHAT I DO</div><h2>Good ideas,<br/><span>made useful.</span></h2></div><p>From a focused proof of concept to a complete product, I build software around the problem it needs to solve.</p></div></Reveal><div className="service-grid">{SERVICES.map((s,i)=>{const Icon=[Bot,Layers3,Cpu,Sparkles][i];return <Reveal key={s.title} delay={i*.06}><article className="service-card"><div className="service-index">0{i+1}</div><div className="service-icon"><Icon size={19}/></div><h3>{s.title}</h3><p>{s.description}</p><span className="service-arrow"><ArrowUpRight size={15}/></span></article></Reveal>})}</div><Reveal><a className="service-cta" href="#contact"><span className="cta-orb"><BriefcaseBusiness size={17}/></span><span><small>HAVE A WORKFLOW OR PRODUCT IDEA?</small><b>Let’s build a prototype.</b></span><span className="cta-link">Tell me about it <ArrowRight size={14}/></span></a></Reveal></div></section>

    <section className="section-pad section-stack"><div className="container stack-layout"><Reveal><div className="section-overline"><span>04</span> VERIFIED IN MY REPOSITORIES</div><h2>Tools behind<br/><span>the work.</span></h2><p className="stack-intro">A snapshot of technologies present in the projects above. Each project card lists its own stack.</p></Reveal><Reveal className="stack-right"><div className="stack-grid">{STACK.map((tech,i)=><div key={tech} className="stack-item"><span className={`stack-symbol stack-${i%7}`}>{tech.slice(0,1)}</span>{tech}</div>)}</div><span className="stack-note"><span/> Practical experience, no percentage bars.</span></Reveal></div></section>

    <section id="about" className="section-pad section-about"><div className="container about-grid"><Reveal><div className="monogram-card"><div className="monogram-grid"/><div className="mono-corner corner-tl"/><div className="mono-corner corner-br"/><div className="monogram">K<span>.</span></div><div className="mono-caption"><span>KA / 01</span><span>INDEPENDENT<br/>BUILDER</span></div><div className="mono-ring ring-one"/><div className="mono-ring ring-two"/></div></Reveal><Reveal className="about-copy"><div className="section-overline"><span>05</span> A LITTLE ABOUT ME</div><h2>ABOUT <span>ME</span></h2><div className="about-name">KAPILASH <span>— AI SOFTWARE ENGINEER</span></div><p>I’m Kapilash, an AI/software developer from Sri Lanka focused on building intelligent software, AI systems, automation tools, developer infrastructure, and experimental technology.</p><p>I learn by building real projects — from research and automation systems to developer tools and full-stack applications. You can explore my public work directly on GitHub.</p><a className="about-github" href={PROFILE.githubUrl} target="_blank" rel="noreferrer"><Github size={15}/> github.com/kapilashkapilash2025-netizen <ArrowUpRight size={13}/></a><a className="button about-github-button" href={PROFILE.githubUrl} target="_blank" rel="noreferrer">Explore my GitHub <ArrowUpRight size={14}/></a><div className="about-facts"><div><small>BASED IN</small><b>Sri Lanka</b></div><div><small>WORKING</small><b>Remote / International</b></div><div><small>AVAILABILITY</small><b><span className="online-dot"/> Selected projects</b></div></div></Reveal></div></section>

    <section className="section-pad section-capabilities"><div className="container capability-layout"><Reveal><div className="section-overline"><span>06</span> PRACTICAL POSSIBILITIES</div><h2>WHAT I CAN<br/><span>BUILD</span></h2><p>Capabilities reflected in my public repositories, from research platforms and local-first dashboards to full-stack web systems.</p></Reveal><Reveal className="capability-right"><div className="capability-list">{CAPABILITIES.map((item,i)=><div key={item} className="capability-item"><span className="cap-number">0{i+1}</span><span>{item}</span><ArrowUpRight size={15}/></div>)}</div><div className="capability-note"><Sparkles size={16}/><p>Need something specific? Tell me the workflow or problem and I’ll propose a technical approach.</p><a href="#contact" aria-label="Discuss a project"><ArrowRight size={16}/></a></div></Reveal></div></section>

    <section id="contact" className="section-pad section-contact"><div className="container"><Reveal><div className="contact-banner"><div className="contact-grid"/><div className="contact-banner-content"><div className="section-overline"><span className="contact-pulse"/> LET’S WORK TOGETHER</div><h2>Have a project<br/>in <span>mind?</span></h2><p>Tell me what you’re trying to automate, build, or improve.</p><div className="contact-actions"><a className="button" href={`mailto:${PROFILE.email}`}>Hire me <ArrowUpRight size={15}/></a><a className="button button-quiet contact-email" href={`mailto:${PROFILE.email}`}><Mail size={15}/> Email me</a></div><div className="email-line">OR WRITE DIRECTLY <a href={`mailto:${PROFILE.email}`}>{PROFILE.email} <ArrowUpRight size={12}/></a></div></div><div className="contact-art" aria-hidden="true"><div className="contact-orbit orbit-a"/><div className="contact-orbit orbit-b"/><div className="contact-sigil"><Command size={48}/></div><span className="orbit-dot dot-a"/><span className="orbit-dot dot-b"/></div></div></Reveal><div className="contact-form-wrap"><Reveal><div className="form-intro"><div className="section-overline"><span>START A CONVERSATION</span></div><h3>What are you<br/>thinking about?</h3><p>Share a few details. Your email app will open with everything ready to send.</p></div></Reveal><Reveal className="form-column"><form className="contact-form" onSubmit={handleForm}><div className="form-row"><label>Name<input required name="name" autoComplete="name" placeholder="Your name"/></label><label>Email<input required name="email" type="email" autoComplete="email" placeholder="you@company.com"/></label></div><label>Company <span className="optional">OPTIONAL</span><input name="company" autoComplete="organization" placeholder="Company or team"/></label><label>What do you want to build?<textarea required name="project" rows={4} placeholder="A quick outline of the problem, idea, or workflow…"/></label><button type="submit" className="button form-submit">Continue with email <ArrowUpRight size={15}/></button></form></Reveal></div></div></section>

    <footer className="footer"><div className="container footer-main"><a href="#home" className="brand"><span className="brand-mark">K<span>.</span></span><span>KAPILASH</span></a><span className="footer-note">Thoughtful software for real-world problems.</span><div className="footer-social"><a href={SOCIALS.github} target="_blank" rel="noreferrer"><Github size={16}/><span>GitHub</span><ArrowUpRight size={12}/></a>{SOCIALS.linkedin && <a href={SOCIALS.linkedin} target="_blank" rel="noreferrer"><Linkedin size={16}/><span>LinkedIn</span><ArrowUpRight size={12}/></a>}</div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} KAPILASH. BUILT WITH INTENTION.</span><a href="#home">BACK TO TOP <ArrowUpRight size={12}/></a></div></footer>
  </main>;
}
